name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the ESP32 project template
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: Describe the feature in one or two sentences...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Build System & Automation
        - WiFi & Networking
        - Monitoring & Debugging
        - Flash Management & Backup
        - OTA Updates
        - Project Management
        - Documentation
        - CI/CD & Workflows
        - Hardware Support
        - Security
        - Performance
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
        Are there existing tools or methods that partially solve this problem?

  - type: textarea
    id: examples
    attributes:
      label: Examples & Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example scenarios where this feature would be useful:
        1. When developing [specific type of project]...
        2. During [specific workflow step]...
        3. For users who need to [specific requirement]...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, share them here
      placeholder: |
        Optional: Share any thoughts on implementation approach:
        - New script files needed
        - Changes to existing files
        - New dependencies
        - Configuration options
        - Command-line interface changes

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Please consider the impact on existing functionality
      options:
        - label: This feature should be backward compatible
          required: false
        - label: This feature may require breaking changes
          required: false
        - label: This feature should be optional/configurable
          required: false
        - label: This feature affects multiple platforms (Windows/Linux/macOS)
          required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
          required: false
        - label: I can help with testing the implementation
          required: false
        - label: I can help with documentation
          required: false
        - label: I can provide feedback during development
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references about the feature request here
      placeholder: |
        Any additional information that might help:
        - Links to similar features in other projects
        - Screenshots or mockups
        - References to documentation or standards
        - Related issues or discussions